### ISSUE TITLE
Compile library with Groovy 1.7 so it's usable with Grails 1.3

### ISSUE THREAD

**Issue by mgryszko** [ldaley/remote-control#9]
After installing the latest 1.4 version of remote control plugin that uses 0.5 version of this library, I'm getting this exception:

```
java.lang.NoClassDefFoundError: org/codehaus/groovy/runtime/BytecodeInterface8
    at groovyx.remote.transport.http.RemoteControlServlet.init(RemoteControlServlet.groovy:32)
```

Seems that after compiling it uses an internal Groovy class available from 1.8 upwards. Would it be possible to compile the library with Groovy 1.7?

**Comment by ldaley** [comment]
It wouldn't be easy to do this. 

Can you use an older version? Groovy 1.7 and Groovy 1.8 are generally not binary compatible.
On 11/04/2013, at 12:05 PM, Marcin Gryszko notifications@github.com wrote:

> After installing the latest 1.4 version of remote control plugin that uses 0.5 version of this library, I'm getting this exception:
> 
> java.lang.NoClassDefFoundError: org/codehaus/groovy/runtime/BytecodeInterface8
>     at groovyx.remote.transport.http.RemoteControlServlet.init(RemoteControlServlet.groovy:32)
> 
> Seems that after compiling it uses an internal Groovy class available from 1.8 upwards. Would it be possible to compile the library with Groovy 1.7?
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Luke Daley.

**Comment by mgryszko** [comment]
Does the library use some Groovy 1.8 specific stuff?

**Comment by ldaley** [comment]
Yeah.

On 11/04/2013, at 12:21 PM, Marcin Gryszko notifications@github.com wrote:

> Does the library use some Groovy 1.8 specific stuff?
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Luke Daley.
